### ISSUE TITLE
Milestone 1

### ISSUE THREAD

**Issue by rantahar** [rdsea/odop#15]
Deadline April

- [x]  - Task specification
- [x]  - Implementation of main decorator and a few UI and integration decorators
- [x]  - Engine runs python and executable
- [x]  - Scheduler running with basic options
- [x]  - Observability module and scheduler running in an HPC task
